name: Tag

env:
  NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  node-version: 20.x

on:
  workflow_dispatch:
  push:
    tags:
      - 'v**'

jobs:
  build:
    uses: micro-lc/compose-toolkit/.github/workflows/build.yml@main

  release-package:
    name: Release package on npm
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn

      - name: Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ./dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish
        run: yarn npm publish
